apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ultimate-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    testing: three
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/bogdan-volynets/argocd-example-apps.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: testing-labels
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
